language: c
sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - WITH_LUA_ENGINE=Lua LUA=lua5.3
    - WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1

    # LuaRocks 3.1.3
    - LUAROCKS=3.1.3 WITH_LUA_ENGINE=Lua LUA=lua5.3
    - LUAROCKS=3.1.3 WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1

os:
  - linux
  - osx

before_install:
  - git submodule update --init --recursive
  - git submodule update --recursive

script:
  - make && make test
  # Setup LuaRocks
  - source .ci/setenv_lua.sh
  # Test rock installation
  - luarocks make
  - test $PWD = `lua -e "print(require'luv'.cwd())"`
  - luarocks remove luv
  # Test the alternate rockspec
  - mkdir build/lib
  - cp build/deps/libuv/libuv_a.a build/lib/libuv.a
  - cp -a deps/libuv/include build
  - luarocks make rockspecs/$(ls rockspecs) LIBUV_DIR=build LUA_COMPAT53_INCDIR=deps/lua-compat-5.3/c-api
  - test $PWD = `lua -e "print(require'luv'.cwd())"`

jobs:
  fast_finish: true
  allow_failures:
    - name: process cleanup test
      os: linux
      env:
        - WITH_LUA_ENGINE=Lua
      script:
        - ./tests/test-sigchld-after-lua_close.sh
  include:
    - stage: sanity checks
      name: clang-asan
      os: linux
      compiler: clang
      env:
        - ASAN_OPTIONS="detect_leaks=1:check_initialization_order=1"
        - UBSAN_OPTIONS="print_stacktrace=1"
        - BUILD_TYPE=Debug
        - WITH_LUA_ENGINE=Lua
      script:
        - CMAKE_OPTIONS="-DCMAKE_C_FLAGS=-fsanitize=address,undefined" make && make test
    - name: valgrind
      os: linux
      addons:
        apt:
          sources:
            # Need a more up-to-date Valgrind to dodge https://bugs.kde.org/show_bug.cgi?id=381289
            - sourceline: 'ppa:jonathonf/development-tools'
          packages:
            - valgrind
      env:
        - BUILD_TYPE=Debug
        - WITH_LUA_ENGINE=Lua
      script:
        - make
        - valgrind --error-exitcode=1 --leak-check=full ./build/lua tests/run.lua
    - name: bindings coverage
      os: linux
      script:
        - ./.ci/bindcov.sh
    - stage: deploy
      if: tag IS present
      env: WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1
      script: skip
      before_deploy:
        - .ci/make_rockspec.sh $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: luv-$TRAVIS_TAG.tar.gz
        overwrite: true
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - luarocks install lua-cjson # required for luarocks upload
        - luarocks upload luv-$TRAVIS_TAG.rockspec --api-key=$LUAROCKS_API_KEY --force

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
